routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\ScoreController;
use App\Http\Controllers\PerformanceAnswersController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('sections', SectionController::class);
    Route::resource('departments',DepartmentController::class);
    Route::resource('sections',SectionController::class);
    Route::resource('questions',QuestionController::class);
    Route::resource('scores',ScoreController::class);
    Route::resource('evaluation',PerformanceAnswersController::class);


    Route::get('employee_performance','App\Http\Controllers\PerformanceAnswersController@display_users_scores')->name('employee_performance');
    Route::get('employee_performance/created_at','App\Http\Controllers\PerformanceAnswersController@search_by_date');

    Route::get('/export-pdf', [App\Http\Controllers\PerformanceAnswersController::class, 'exportPdf'])->name('export-pdf');

    Route::get('/summary-pdf/{id}', [App\Http\Controllers\PerformanceAnswersController::class, 'summaryPdf'])->name('summary-pdf');



});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/search','App\Http\Controllers\PerformanceAnswersController@search_by_date');

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('dashboard');


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::patch('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::patch('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
});

resources/views/peformance_evaluation/admin.blade.php
@extends('layouts.app', ['activePage' => 'evaluation', 'title' => 'Peformance Evaluation', 'navName' => 'Evalaution'])


@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card strpied-tabled-with-hover">
                        <div class="card-header ">
                            <h4 class="card-title">Peformance Evaluation Scores</h4>
                            <div class="pull-right">
                    <a class="btn btn-secondary" href="{{ route('export-pdf') }}"> Download</a>
                </div>

                        </div>

                   
                        
                        <div class="card-body table-full-width table-responsive">
                            <table id="evaluation_table" class="table table-hover table-striped">
                                <thead>
                                    <!-- <th>Id</th> -->
                                    <th>Employee Name</th>
                                    <th>Total Score</th>
                                    <th> Actions</th>
                          
                                    
                                    <!-- <th>Actions</th> -->
                                </thead>
                                <tbody>
                                    
                                @foreach( $scores as $score )
                                    <tr>
                                        <!-- <td>{{$score->id}}</td> -->
                                        <td>{{$score->name}}</td>
                                        <!-- <td>{{$score->Section_name}}</td> -->
                                        <td>{{$score->sum}}</td>
                                        <td> 
                                            <a  class="btn btn-info " href="{{ route('evaluation.show',$score->user_id) }}">View</a>
                                            <a  class="btn btn-primary" href="{{ route('evaluation.edit',$score->user_id) }}">Edit</a> 
                                            <a  class="btn btn-success" href="{{ route('summary-pdf',$score->user_id) }}">Download</a> 

                                        </td>

                                        </td>
                         
                                    </tr>
                                </tbody>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
             
            </div>
        </div>
    </div>

    <script>
    $(document).ready(function() {
        $('#evaluation_table').DataTable();
    });
</script>
@endsection

resources/views/peformance_evaluation/create.blade.php
@extends('layouts.app', ['activePage' => 'evalaution', 'title' => 'Peformance Evaluation', 'navName' => 'Evalaution'])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
        <form method="post" action="{{route('evaluation.store')}}" autocomplete="off" class="form-horizontal" enctype="multipart/form-data" >
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <!-- <h4 class="card-title">{{ __('Add Score') }}</h4> -->
                <p class="card-category"></p>
              </div>

              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{route('scores.index')}}" class="btn btn-sm btn-outline-success">{{ __('Back') }}</a>
                  </div>
                </div>

             
             


                @foreach( $questions as $question )

                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Question No:') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="input-name"  name="Question_id" type="text" value="{{$question->id}}" required="true" aria-required="true" readonly/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
              
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Section Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="input-name" name="Section_id" type="text" value="{{$question->section->id}}" required="true" aria-required="true" readonly/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>

                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Question:') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"  id="input-name" type="text" value="{{$question->Score_Category}}" required="true" aria-required="true" readonly/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>



                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Score') }}</label>
                  <div class="col-sm-7">
                    <select class="form-control" name="Score_value">
                        <option></option>
                        @foreach ($question->scores as $score) 
                            <option value="{{$score->Values}} " {{ ( $score->Score_Name) ? 'selected' : '' }}> 
                            {{$score->Score_Name}} :Value = {{$score->Values}}  
                            </option>
                        @endforeach    
                    </select>
                  </div>
                </div>
<br>
@endforeach  
             
                <br>

              
                                 
              </div>
             <div class="card-footer ml-auto mr-auto">
                <!-- {{-- <button type="submit" class="btn btn-warning btn-block">{{ __('Add') }}</button> --}} -->
                <button type="submit" class="btn btn-warning btn-block ">
                  {{ __('Submit')}}
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/peformance_evaluation/edit.blade.php
@extends('layouts.app', ['activePage' => 'evalaution', 'title' => 'Peformance Evaluation', 'navName' => 'Evalaution'])


@section('content')
<div class="content">
    <div class="container-fluid">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h4>Edit Report </h4>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('evaluation.index') }}"> Back</a>
        </div>
    </div>
</div>

@if (count($errors) > 0)
  <div class="alert alert-danger">
    <label class="col-sm-2 col-form-label">Whoops!</label> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
@endif

<form action="{{route('performance_answers.update',$performance_answers->Score_value)}}" method="POST">
@csrf
@method('PUT')

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <label class="col-sm-2 col-form-label">Score Value:</label>
            <input type="text" name="Section_Name" value="{{$performance_answers->Score_value}}" class="form-control" placeholder="Section Name">
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
{!! Form::close() !!}


</div>
</div>

@endsection

resources/views/peformance_evaluation/index.blade.php
@extends('layouts.app', ['activePage' => 'scores', 'title' => 'Scores', 'navName' => 'Scores'])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{route('scores.store')}}" autocomplete="off" class="form-horizontal" enctype="multipart/form-data" >
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Add Score') }}</h4>
                <p class="card-category"></p>
              </div>

              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{route('scores.index')}}" class="btn btn-sm btn-outline-success">{{ __('Back') }}</a>
                  </div>
                </div>

              
               <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Score Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="Score_Name" id="input-name" type="text" placeholder="{{ __('Score Name') }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>

                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Question') }}</label>
                  <div class="col-sm-7">
                    <select class="form-control" name="Question_id">
                        <option></option>
                        @foreach ($questions as $question=> $value)
                            <option value="{{ $question}}" {{ ( $question) ? 'selected' : '' }}> 
                                {{ $value }} 
                            </option>
                        @endforeach    
                    </select>
                  </div>
                </div>
<br>
                   
               <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Score Value') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="Values" id="input-name" type="text" placeholder="{{ __('Score Value') }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>

                <br>

              
                                 
              </div>
             <div class="card-footer ml-auto mr-auto">
                <!-- {{-- <button type="submit" class="btn btn-warning btn-block">{{ __('Add') }}</button> --}} -->
                <button type="submit" class="btn btn-warning btn-block ">
                  {{ __('Add')}}
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/peformance_evaluation/questions.blade.php
@extends('layouts.app', ['activePage' => 'evalaution', 'title' => 'Peformance Evaluation', 'navName' => 'Evalaution'])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card strpied-tabled-with-hover">
                        <div class="card-header ">
                            <h4 class="card-title">Peformance Evaluation</h4>
                            <!-- <a class="btn btn-success" href="{{ route('scores.create') }}"> Create New Score</a> -->

                            <!-- <p class="card-category">Here is a subtitle for this table</p> -->
                        </div>
                        <div class="card-body table-full-width table-responsive">
                   
        
                            <table class="table table-hover table-striped">
                                <thead>
                                    <!-- <th>Id</th>
                                    <th>Questions</th>
                                    <th>Section</th>
                                    <th class="pull-right">Scores</th> -->
                                    
                                    <!-- <th>Actions</th> -->
                                </thead>
                                <tbody>
                                <form method="post" action="{{route('evaluation.store')}}" autocomplete="off" class="form-horizontal" enctype="multipart/form-data" >
            @csrf
            @method('post')
                                @foreach( $questions as $question )
                      

                                <tr>
                                    <td>{{$question->section->Section_Name}}</td>   
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
</tr>
                                    <tr>
                                
                                    <td></td>
                                    @foreach ($question->scores as $score)  
                                  
                                    <td> 
                    <input type="checkbox" name="Score_value" value="{{$score->id}}">  {{$score->Score_Name}} 
           


                            
                                    </td>    @endforeach  
                                    </tr>
                                    
<tr>
<td></td>
@foreach ($question->scores as $score)  
<td> 
{{$score->Values}} 
                                    </td>    @endforeach  

</tr>

<tr>
<td>{{$question->Score_Category}}</td>
@foreach ($question->scores as $score)  
<td>
{{$score->Description}} 
                                    </td>    @endforeach  
</tr>
    
                                </tbody>
                                @endforeach
                  
                            </table>
                                      
               
                <button type="submit" class="btn btn-warning btn-block">{{ __('Submit') }}</button> 
                <!-- <button type="submit" class="btn btn-warning btn-block ">
                  {{ __('Submit')}}
                </button> -->

</form>
                        </div>
                    </div>
                </div>
             
            </div>
        </div>
    </div>
@endsection

resources/views/peformance_evaluation/show.blade.php
@extends('layouts.app', ['activePage' => 'evalaution', 'title' => 'Peformance Evaluation', 'navName' => 'Evalaution'])


@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card strpied-tabled-with-hover">
                        <div class="card-header ">
                            
                            <h4 class="card-title">Peformance Evaluation Scores</h4>
                            <!-- <a class="btn btn-success" href="{{ route('scores.create') }}"> Create New Score</a> -->

                            <!-- <p class="card-category">Here is a subtitle for this table</p> -->
                        </div>

                     
                        <div class="card-body table-full-width table-responsive">

                            <table id="performance_table" class="table table-hover table-striped">

                                <thead>
                                    <!-- <th>Id</th> -->
                                    <th>Employee Name</th>
                                    <th>Section Name</th>
                                    <th>Total Score</th>
                                    <th> Date</th>
                          
                                    
                                    <!-- <th>Actions</th> -->
                                </thead>
                                <tbody>
                                @foreach( $scores as $score ) 
                                    <tr>
                                        <!-- <td>{{$score->id}}</td> -->
                                        <td>{{$score->name}}</td>
                                        <td>{{$score->Section_name}}</td>
                                        <td>{{$score->sum}}</td>
                                        <td>{{$score->created_at->format('Y-m-d') }}</td>
  
                         
                                    </tr>
                                </tbody>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
             
            </div>
        </div>
    </div>
    <script>
    $(document).ready(function() {
        $('#performance_table').DataTable({});
    });
</script>
@endsection