routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\SectionController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\ScoreController;
use App\Http\Controllers\PerformanceAnswersController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('sections', SectionController::class);
    Route::resource('departments',DepartmentController::class);
    Route::resource('sections',SectionController::class);
    Route::resource('questions',QuestionController::class);
    Route::resource('scores',ScoreController::class);
    Route::resource('evaluation',PerformanceAnswersController::class);


    Route::get('employee_performance','App\Http\Controllers\PerformanceAnswersController@display_users_scores')->name('employee_performance');
    Route::get('employee_performance/created_at','App\Http\Controllers\PerformanceAnswersController@search_by_date');

    Route::get('/export-pdf', [App\Http\Controllers\PerformanceAnswersController::class, 'exportPdf'])->name('export-pdf');

    Route::get('/summary-pdf/{id}', [App\Http\Controllers\PerformanceAnswersController::class, 'summaryPdf'])->name('summary-pdf');



});
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/search','App\Http\Controllers\PerformanceAnswersController@search_by_date');

Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('dashboard');


Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::patch('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::patch('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::get('{page}', ['as' => 'page.index', 'uses' => 'App\Http\Controllers\PageController@index']);
});

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use HasFactory;


    public function section()
    {
        return $this->hasOne('App\Models\Section', 'id', 'Section_id');
        
    }

    public function scores()
    {
        return $this->hasMany('App\Models\Score', 'Question_id', 'id');
    }



}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Question;
use App\Models\Section;
use DataTables;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
    
        $questions = Question::with('section')->orderBy('id', 'ASC')->get();
        // return response()->json($questions);

        if ($request->ajax()) {
            return Datatables::of($questions)
                    ->addIndexColumn()
                    ->addColumn('action', function($row){
                        $btn = '<a href="javascript:void(0)" class="edit btn btn-primary btn-sm">View</a>';
                        return $btn;
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        return view('questions.index',compact('questions'));


    }

    public function perfomance()
    {
    
        $questions = Question::with('section','scores')->orderBy('id', 'ASC')->get();

        return view('peformance_evaluation.questions',compact('questions'));
        
        // return response()->json($questions);



    }






    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    //    $sections = Section::orderBy('id', 'ASC')->get();
        $sections = Section::pluck('Section_Name', 'id');

        return view('questions.create',compact('sections'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            // 'Description' => 'required',
            'Question_Category' => 'required',
            'Section_id' => 'required',
        ]);
       
        $question = new Question;
        // $question->Description = $request->Description;
        $question->Question_Category = $request->Question_Category;
        $question->Section_id = $request->Section_id;
        try{
            $question->save();
            return redirect()->route('questions.index');
        } catch (\Illuminate\Database\QueryException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $question = Question::find($id);
        $sections = Section::pluck('Section_Name', 'id');
        return view('questions.show',compact('question'));
        


    }
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $questions = Question::find($id);
        $sections = Section::find('Section_Name','id');
    
        return view('questions.edit',compact('questions','sections'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate([
            'Description' => 'required',
            'Score_Category' => 'required',
            'Section_id' => 'required',
        ]);
       
        $question = Question::whereId($request->id)->first();
        $question->Description = $request->Description;
        $question->Score_Category = $request->Score_Category;
        $question->Section_id = $request->Section_id;

        try{
           $question->save();
            return response()->json($question);
        } catch (\Illuminate\Database\QueryException $e) {
            return response()->json(['status' => 'error', 'message' => $e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $question = Question::findOrFail($id);
        $question->delete();
        return redirect()->route('questions.index');
    }
}

resources/views/questions/create.blade.php
@extends('layouts.app', ['activePage' => 'Questions', 'title' => 'Questions', 'navName' => 'Performance Questions'])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{route('questions.store')}}" autocomplete="off" class="form-horizontal" enctype="multipart/form-data" >
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Add Question') }}</h4>
                <p class="card-category"></p>
              </div>

              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{route('questions.index')}}" class="btn btn-sm btn-outline-success">{{ __('Back') }}</a>
                  </div>
                </div>

              
               <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Question Category') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="Question_Category" id="input-name" type="text" placeholder="{{ __('Question') }}" required="true" aria-required="true"/>
                      @if ($errors->has('name'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>

                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Section') }}</label>
                  <div class="col-sm-7">
                    <select class="form-control" name="Section_id">
                        <option></option>
                        @foreach ($sections as $section=> $value)
                            <option value="{{ $section}}" {{ ( $section) ? 'selected' : '' }}> 
                                {{ $value }} 
                            </option>
                        @endforeach    
                    </select>
                  </div>
                </div>

                <br>

              
                                 
              </div>
             <div class="card-footer ml-auto mr-auto">
                <!-- {{-- <button type="submit" class="btn btn-warning btn-block">{{ __('Add') }}</button> --}} -->
                <button type="submit" class="btn btn-warning btn-block ">
                  {{ __('Add')}}
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app', ['activePage' => 'Question Management', 'title' => 'Questions', 'navName' => 'Question Management'])

@section('content')
<div class="content">
    <div class="container-fluid">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h4>Edit Question</h4>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('questions.index') }}"> Back</a>
        </div>
    </div>
</div>

@if (count($errors) > 0)
  <div class="alert alert-danger">
    <label class="col-sm-2 col-form-label">Whoops!</label> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
@endif

<form action="{{route('questions.update',$questions->Score_Category)}}" method="POST">
@csrf
@method('PUT')

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <label class="col-sm-2 col-form-label">Question Name:</label>
            <input type="text" name="Score_Category" value="{{$questions->Score_Category}}" class="form-control" placeholder="Section Name">
        </div>
    </div>
    <div class = "col-xs-12 col-sm-12 col-md-12">
<div class="row">
    <div class ="col-xs-12 col-sm-12 col-md-12">
        <div class= "form-group">
            <label class="col-sm-2 col-form-label">{{ __('Section') }}</label>
            <div class="col-sm-7">
                    <select class="form-control" name="Section_id">
                        <option></option>
                            <option value="{{$questions}}" {{ ( $sections) ? 'selected' : '' }}> 
                                {{ $sections }} 
                            </option>
                    </select>
                  </div>
                </div>
            </div>
        </div>

    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

{!! Form::close() !!}


</div>
</div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app', ['activePage' => 'questions', 'title' => 'Questipns', 'navName' => 'Questions'])

@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card strpied-tabled-with-hover">
                        <div class="card-header ">
                            <h4 class="card-title">Perfomance Questions</h4>
                            <div class="pull-right">
                    <a class="btn btn-success" href="{{ route('questions.create') }}"> Create New Questions</a>
                </div>
                            <!-- <p class="card-category">Here is a subtitle for this table</p> -->
                        </div>
                        <div class="card-body table-full-width table-responsive">
                            <table id="performance_table" class="table">
                                <thead>
                                    <!-- <th>Id</th>
                                    <th>Question</th> -->
                                     <th>Question Category</th>
                                     <th>Section</th>
                                    <th>Actions</th>
                                </thead>
                                <tbody>
                                @foreach( $questions as $question )
                                    <tr>
                                        <!-- <td>{{$question->id}}</td>
                                        <td>{{$question->Description}}</td> -->
                                        <td>{{$question->Score_Category}}</td>
                                        <td>{{$question->section->Section_Name}}</td>
                                        <td>
                                            <a class="btn btn-info" href="{{ route('questions.show',$question->id) }}">Show</a>
                                            <a class="btn btn-primary" href="{{ route('questions.edit',$question->id) }}">Edit</a>
                                                {!! Form::open(['method' => 'DELETE','route' => ['questions.destroy', $question->id],'style'=>'display:inline']) !!}
                                                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                                {!! Form::close() !!}
                                        </td>
                         
                                    </tr>
                                </tbody>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>
             
            </div>
        </div>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
  $(function () {
    var table = $('.data-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('users.index') }}",
        columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex'},
            {data: 'name', name: 'Question Category'},
            {data: 'email', name: 'Section'},
            {data: 'action', name: 'Actions', orderable: false, searchable: false},
        ]
    });
</script>

@endsection

resources/views/questions/show.blade.php
@extends('layouts.app', ['activePage' => 'Questions', 'title' => 'Questions', 'navName' => 'Questions'])


@section('content')
<div class="content">
    <div class="container-fluid">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show Question</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
        </div>
    </div>
</div>


<div class="row">
<div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Section Name:</strong>
            {{$question->section->Section_Name}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Question Category:</strong>
            {{$question->Score_Category}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Description:</strong>
            {{$question->Description }}
        </div>
    </div>
</div>
</div>
</div>
@endsection